<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Codex20.Ingestion</RootNamespace>
    <UserSecretsId>5e89bb5e-a711-4de5-821f-dc01f5271316</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\..\TestesC#\TestesC#\Data\Resultados\RESULTADO_GuiaDoMestre.json" Link="Data\Json\RESULTADO_GuiaDoMestre.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\TestesC#\TestesC#\Data\Resultados\RESULTADO_LivroDoJogador.json" Link="Data\Json\RESULTADO_LivroDoJogador.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\TestesC#\TestesC#\Data\Resultados\RESULTADO_manualMonstro.json" Link="Data\Json\RESULTADO_manualMonstro.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.AI.DocumentIntelligence" Version="1.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Codex20.Core\Codex20.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Data\Markdown\" />
    <Folder Include="Data\Json\" />
    <Folder Include="Data\PDF\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\TestesC#\TestesC#\Data\GuiaDoMestre.pdf" Link="Data\PDF\GuiaDoMestre.pdf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="..\..\TestesC#\TestesC#\Data\LivroDoJogador.pdf" Link="Data\PDF\LivroDoJogador.pdf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="..\..\TestesC#\TestesC#\Data\manualMonstro.pdf" Link="Data\PDF\manualMonstro.pdf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="..\..\TestesC#\TestesC#\Data\Resultados\RESULTADO_GuiaDoMestre.md" Link="Data\Markdown\RESULTADO_GuiaDoMestre.md">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="..\..\TestesC#\TestesC#\Data\Resultados\RESULTADO_LivroDoJogador.md" Link="Data\Markdown\RESULTADO_LivroDoJogador.md">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="..\..\TestesC#\TestesC#\Data\Resultados\RESULTADO_manualMonstro.md" Link="Data\Markdown\RESULTADO_manualMonstro.md">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
